# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'
use_modular_headers!
target 'TodoListWithUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks

pod 'FlexLayout'
pod 'PinLayout'
pod 'RxSwift', '6.7.1'
pod 'RxCocoa', '6.7.1'
  # Pods for TodoListWithUIKit

end
